### ISSUE TITLE
Add 'media' tab

### ISSUE THREAD

**Issue by jnewbery** [bitcoinbrink/website#18]
We should have a tab similar to https://dci.mit.edu/press. It should include contact details for inbound media inquiries, and links to stories about Brink:

- [Bitcoin Magazine - John Newbery’s New Nonprofit Brink Will Train And Support Bitcoin Developers](https://bitcoinmagazine.com/articles/john-newberys-new-nonprofit-brink-will-train-and-support-bitcoin-developers)
- [Coindesk - Square, Human Rights Foundation Back New Bitcoin Open-Source Developer Fund](https://www.coindesk.com/bitcoin-developer-john-newbery-brink-open-source-fund-square-hrf)
- [Bitcoin Magazine - Gloria Zhao And Brink Are Set To Give Bitcoin Mempools An Upgrade](https://bitcoinmagazine.com/articles/gloria-zhao-and-brink-are-set-to-give-bitcoin-mempools-an-upgrade)
- [On The Brink - John Newbery (Brink) on funding Bitcoin development](https://onthebrink-podcast.com/brink/)
- [The Stephan Livera Podcast - JOHN NEWBERY – BRINK: BITCOIN DEVELOPMENT](https://stephanlivera.com/episode/229/)
- [What Bitcoin Did - Funding Bitcoin Development with John Newbery](https://www.whatbitcoindid.com/podcast/funding-bitcoin-development)

**Comment by jnewbery** [comment]
@bitschmidty any thoughts about this?

**Comment by bitschmidty** [comment]
Concept ack for sure!

Want me to take a crack at it?

**Comment by jnewbery** [comment]
Yes please!
