### ISSUE TITLE
Press coverage

### ISSUE THREAD

**Issue by jnewbery** [bitcoinbrink/website#34]
- BTC Times: https://www.btctimes.com/news/brink-awards-three-developer-grants
- Bitcoin Magazine: https://bitcoinmagazine.com/business/brink-awards-three-bitcoin-development-grants
- Bitcoin Magazine Podcast: https://bitcoinmagazine.com/culture/optimizing-bitcoin-with-gloria-zhao . I haven't listened to this yet. I'm just going to assume that @glozow says nice things about Brink :)

**Comment by jnewbery** [comment]
Mind taking this one, @bitschmidty?

**Comment by glozow** [comment]
> I'm just going to assume that @glozow says nice things about Brink :)

Always!

**Comment by jnewbery** [comment]
Closed by #36
