### ISSUE TITLE
blog post: what it's like to be a brink grantee

### ISSUE THREAD

**Issue by jnewbery** [bitcoinbrink/website#67]
https://brink.dev/news/2021/08/05/grant-process.html does a good job at differentiating us from other grant-giving entities in the way that we handle applications.

I think another way that we're different is the way that we take care of our grantees after we've accepted them. For example:

- all grantees have regular (monthly) status calls with a technical expert. That shows our donors that we're doing our diligence and the grantees that we're taking an interest in their work.
- we have a regular engineering calls where grantees present their work to a group of peers
- we have a slack channel where we discuss issues and share stuff
- we encourage them to speak at conferences, promote their work, etc
- we're good at the basic logistical stuff like making sure they get paid promptly, being responsive to emails, etc

I think it's worth publicizing all that. What do you think @harding @bitschmidty ?

**Comment by jnewbery** [comment]
Perhaps we could use quotes from our existing grantees

**Comment by harding** [comment]
Definitely worth publicizing.  Could be done on its own, or the info could be worked into something else like a year-end blog post where we highlight not only all the work done by grantees, fellows, and staff but also incorporate the above information either as exposition or through quotes from the grantees.
